# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SqliteTableVeiw' do

  use_frameworks!
  pod 'KVOController'
  pod 'FMDB' 


  inhibit_all_warnings!

end
